#!/usr/bin/env bash
# vim: set tabstop=4 expandtab autoindent smartindent:
# author: Sylvain Rabot <sylvain@abstraction.fr>
# date: 25/03/2011
# copyright: All rights reserved

sudo su -c "echo 3 > /proc/sys/vm/drop_caches"
