#!/usr/bin/env bash
# vim: set tabstop=4 expandtab autoindent smartindent:
# author: Sylvain Rabot <sylvain@abstraction.fr>
# date: 24/03/2011
# copyright: All rights reserved

STREAM_REALPATH=$(realpath $0)
CONTRIB_PATH=$(dirname $STREAM_REALPATH)
MIKE_PATH=$(dirname $CONTRIB_PATH)

# -- mike.conf -----------------------------------------------------------------

if [ ! -f "$MIKE_PATH/mike.conf" ]; then
    echo >&2 "$MIKE_PATH/mike.conf not found"
    echo >&2 "You need to execute autoconf && ./configure"
    exit 1
fi

source "$MIKE_PATH/mike.conf"

# -- mike.sh -------------------------------------------------------------------

source "$MIKE_PATH/lib/mike.sh"

# -- usage ---------------------------------------------------------------------

usage()
{
    echo >&2 "$0 usage:"
    echo >&2 "  fill account with inodes"
    echo >&2 ""
    echo >&2 "   --detach       lauch jobs in detach mode"
    echo >&2 "   --jobs         number of parallel jobs (imply --detach)"
    echo >&2 "   --dirs         dirs by level (Default: 5,5,5,5)"
    echo >&2 "   --files        files by level (Default: 5,5,5,5)"
    echo >&2 "   --versioning   enable versioning (Default: No)"
}

# ------------------------------------------------------------------------------

ARGV=`$GETOPT --long h,help,jobs:,dirs:,files:,detach,versioning -n "$0" -- $0 $@`

if [ $? != 0 ] ; then
    die "Terminating ...";
fi

eval set -- "$ARGV"

# ------------------------------------------------------------------------------

MOD="1"
REMAINDER=
DIR_BY_LEVEL="5,5,5,5"
FILE_BY_LEVEL="5,5,5,5"
VERSIONING="false"
DETACH=
SLEEP_TIME=0.3

while true ;
do
    case "$1" in
        --jobs)         MOD="$2";               shift 2;;
        --dirs)         DIR_BY_LEVEL="$2";      shift 2;;
        --files)        FILE_BY_LEVEL="$2";     shift 2;;
        --versioning)   VERSIONING="true";      shift;;
        --detach)       DETACH="true";          shift;;
        --)             shift;                  break;;
        -h|--help)      usage;                  exit 0;;
        *)              usage;                  exit 1;;
    esac
done

# -- config --------------------------------------------------------------------

if [ -z "${DATABASE_HOST}" ]; then
    PSQL_FULL_CMD="$PSQL -U${DATABASE_USER} -d ${DATABASE_NAME} --tuples-only --no-align"
    PSQL_FULL_CMD_ALIGNED="$PSQL -U${DATABASE_USER} -d ${DATABASE_NAME} --tuples-only"
else
    PSQL_FULL_CMD="$PSQL -U${DATABASE_USER} -d ${DATABASE_NAME} -h ${DATABASE_HOST} --tuples-only --no-align"
    PSQL_FULL_CMD_ALIGNED="$PSQL -U${DATABASE_USER} -d ${DATABASE_NAME} -h ${DATABASE_HOST}"
fi

# -- main ----------------------------------------------------------------------

if [ "$MOD" -gt "1" ]; then
    for id_user in $($PSQL_FULL_CMD -c "SELECT id_user FROM mike.user $WHERE;"); do
        $PSQL_FULL_CMD_ALIGNED -c "SELECT * FROM __make_tree($id_user, ARRAY[$DIR_BY_LEVEL], ARRAY[$FILE_BY_LEVEL], $VERSIONING);" > /dev/null 2>&1 &
        PIDS["$!"]="true"
        
        echo "stream started: `strlpad $! 7 ' '` [${#PIDS[@]}]"
        
        # waiting for finished jobs if limit reached
        while [ "${#PIDS[@]}" -ge "$MOD" ]; do
            for pid in "${!PIDS[@]}"; do
                if [ $(ps ax | grep -E "^ *$pid" | wc -l) -eq "0" ]; then
                    echo "stream finished: `strlpad $pid 6 ' '`"
                    unset PIDS[$pid];
                fi
            done
            
            sleep $SLEEP_TIME
        done
    done;
    
    # waiting for remaining jobs
    while [ "${#PIDS[@]}" -gt "0" ]; do
        for pid in "${!PIDS[@]}"; do
            if [ $(ps ax | grep "^$pid"  | wc -l) -eq "0" ]; then
                echo "stream finished: `strlpad $pid 6 ' '`"
                unset PIDS[$pid];
            fi
        done

        sleep $SLEEP_TIME
    done 
else
    for id_user in $($PSQL_FULL_CMD -c "SELECT id_user FROM mike.user $WHERE;"); do
        if [ -z "$DETACH" ]; then
            $PSQL_FULL_CMD_ALIGNED -c "SELECT * FROM __make_tree($id_user, ARRAY[$DIR_BY_LEVEL], ARRAY[$FILE_BY_LEVEL], $VERSIONING);"
        else
            $PSQL_FULL_CMD_ALIGNED -c "SELECT * FROM __make_tree($id_user, ARRAY[$DIR_BY_LEVEL], ARRAY[$FILE_BY_LEVEL], $VERSIONING);" 2> /dev/null &
        fi
    done;
fi

exit 0
