language: c

before_install:
    - sudo service postgresql stop || true
    - sudo apt-get update -qq
    - sudo apt-get install -qq realpath build-essential autoconf postgresql-${POSTGRESQL_VERSION} postgresql-contrib-${POSTGRESQL_VERSION} postgresql-server-dev-${POSTGRESQL_VERSION} postgresql-plperl-${POSTGRESQL_VERSION} libpq-dev
    - test -z "${MAKE_DOC}" || sudo apt-get install -qq asciidoc source-highlight

before_script:
    - sudo service postgresql start ${POSTGRESQL_VERSION}

script:
    - autoconf
    - test -z "${MAKE_DOC}" || ./configure
    - test -z "${MAKE_DOC}" || make doc
    - test -z "${MAKE_DOC}" || make clean
    - test -z "${MAKE_INSTALL}" || ./configure --enable-create-database --enable-dev-mode
    - test -z "${MAKE_INSTALL}" || make drop-database install dev-volumes
    - test -z "${MAKE_INSTALL}" || make test
    - test -z "${MAKE_INSTALL}" || make clean
    - test -z "${MAKE_INSTALL}" || ./configure --enable-create-database --enable-dev-mode --enable-no-atime
    - test -z "${MAKE_INSTALL}" || make drop-database install dev-volumes
    - test -z "${MAKE_INSTALL}" || make test
    - test -z "${MAKE_INSTALL}" || make clean
    - test -z "${MAKE_INSTALL}" || ./configure --enable-create-database --enable-dev-mode --enable-no-atime --enable-lvm-support
    - test -z "${MAKE_INSTALL}" || make drop-database install dev-volumes
    - test -z "${MAKE_INSTALL}" || make test
    - test -z "${MAKE_INSTALL}" || make clean
    - test -z "${MAKE_INSTALL}" || ./configure --enable-create-database
    - test -z "${MAKE_INSTALL}" || make drop-database
    - test -z "${MAKE_INSTALL}" || sudo make install
    - test -z "${MAKE_INSTALL}" || make dev-volumes
    - test -z "${MAKE_INSTALL}" || make test
    - test -z "${MAKE_INSTALL}" || make clean

env:
    global:
        - DATABASE_USER=postgres
        - DATABASE_NAME=mike
        - SLEEP_TIME=0
        - POSTGRESQL_VERSION=9.3
    matrix:
        - MAKE_DOC=1
        - MAKE_INSTALL=1 POSTGRESQL_VERSION=9.1
        - MAKE_INSTALL=1 POSTGRESQL_VERSION=9.2
        - MAKE_INSTALL=1 POSTGRESQL_VERSION=9.3
