#!/usr/bin/env bash

MIKE_VERSION_FILE=MIKE_VERSION_FILE
MIKE_HEAD_DIFF_FILE=MIKE_HEAD_DIFF_FILE
MIKE_TAG_DIFF_FILE=MIKE_TAG_DIFF_FILE

# MIKE_VERSION_FILE
if [ ! -z $1 ]; then
    MIKE_VERSION_FILE=$1;
fi

# MIKE_COMMIT_DIFF_FILE
if [ ! -z $2 ]; then
    MIKE_HEAD_DIFF_FILE=$2
fi

# MIKE_TAG_DIFF_FILE
if [ ! -z $3 ]; then
    MIKE_TAG_DIFF_FILE=$3
fi

MIKE_COMMIT=$(git show-ref $(cat .git/HEAD) | cut -d ' ' -f1)
MIKE_BRANCH=$(git symbolic-ref HEAD 2>/dev/null | sed -e 's#refs/heads/##')
MIKE_WHO=$(whoami)@$(hostname)

if [ ! -z "$(git describe --match "v[0-9]*.[0-9]*.[0-9]*" --dirty 2>/dev/null)" ]; then
    MIKE_VERSION=$(git describe --match "v[0-9]*.[0-9]*.[0-9]*" --dirty --abbrev 2>/dev/null)
    MIKE_LAST_TAG=$(git describe --match "v[0-9]*.[0-9]*.[0-9]*" --no-abbrev 2>/dev/null)

    if [ ! -z "$(git diff --name-only $MIKE_LAST_TAG HEAD --)" ]; then
        echo "$(git diff --patience --no-color $MIKE_LAST_TAG HEAD --)" > $MIKE_TAG_DIFF_FILE
    else
        rm -f $MIKE_TAG_DIFF_FILE
    fi
fi

if [ ! -z "$(git diff-index --name-only HEAD --)" ]; then
    MIKE_COMMIT="$MIKE_COMMIT-dirty";
    echo "$(git diff --patience --no-color HEAD --)" > $MIKE_HEAD_DIFF_FILE
else
    rm -f $MIKE_HEAD_DIFF_FILE
fi

echo "MIKE_VERSION=$MIKE_VERSION" >> $MIKE_VERSION_FILE
echo "MIKE_COMMIT=$MIKE_COMMIT" >> $MIKE_VERSION_FILE
echo "MIKE_BRANCH=$MIKE_BRANCH" >> $MIKE_VERSION_FILE
echo "MIKE_WHO=$MIKE_WHO" >> $MIKE_VERSION_FILE

exit 0
