#!/bin/sh
#
# An example hook script for the "post-receive" event.
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for a sample, or uncomment the next line and
# rename the file to "post-receive".

# -- stdin ---------------------------------------------------------------------

read STDIN

OLDREF=$(echo "$STDIN" | cut -d ' ' -f1)
NEWREF=$(echo "$STDIN" | cut -d ' ' -f2)
REFNAME=$(echo "$STDIN" | cut -d ' ' -f3)

# -- gitstats ------------------------------------------------------------------

GITSTATS=$(which gitstats)
export PWD=`pwd`

if test -n "$GITSTATS"; then
    if test "$REFNAME" = "refs/heads/master"; then
        $GITSTATS $PWD  gitstats > /dev/null 2>&1

        if test "$?" != "0"; then
            echo "gitstats failed ..."
        fi
    fi
fi
